version: '3'

services:
  data-checker:
    build: .
    container_name: data-checker
    environment:
      - TELEGRAM_BOT_TOKEN=ВАШ_TELEGRAM_BOT_TOKEN
      - TELEGRAM_CHAT_ID=ВАШ_CHAT_ID
      - TZ=Europe/Moscow
    volumes:
      - ./data:/app/data
    restart: always
